//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vscap.rc
//
#define IDC_HIGHLIGHTCOLOR              3
#define ID_ABOUT                        3
#define IDSELECT                        3
#define IDOPTIONSCAPTION                3
#define ID_FONT                         3
#define ID_MANUALCONFIG                 3
#define IDFONT                          3
#define IDBKCOLOR                       3
#define IDRESET                         3
#define IDNEXT                          3
#define IDVOLUME                        4
#define ID_CONFIGURE                    4
#define IDOPTIONSDATE                   4
#define ID_TEXTCOLOR                    4
#define ID_JUSTLEFT                     4
#define IDLOAD                          4
#define IDOPTIONSGRAPHICS               5
#define ID_BGCOLOR                      5
#define ID_AUTOCONFIG                   5
#define ID_JUSTCENTER                   5
#define ID_JUSTRIGHT                    6
#define IDFONT2                         7
#define IDD_CURSOROPTIONS               132
#define IDB_BITMAP2                     134
#define IDB_SCREENANNOTATIONS_SMALL     134
#define IDI_ICON1                       135
#define IDI_CUSTOMICON_CONTEXTHELP      136
#define IDI_CUSTOMICON_MAGNIFY          137
#define IDI_CUSTOMICON_NODRAG           138
#define IDI_CUSTOMICON_SPLITBARH        139
#define IDI_CUSTOMICON_SPLITBARV        140
#define IDI_CUSTOMICON_TOPOFTABLE       141
#define IDI_CUSTOMICON_BOOK1            142
#define IDI_CUSTOMICON_BOOK2            143
#define IDI_CUSTOMICON_CLIP1            144
#define IDI_CUSTOMICON_CLIP2            145
#define IDI_CUSTOMICON_CLOCK1           146
#define IDI_CUSTOMICON_CLOCK2           148
#define IDI_CUSTOMICON_CARDFILE1        149
#define IDI_CUSTOMICON_CARDFILE2        150
#define IDI_CUSTOMICON_DISK1            151
#define IDI_CUSTOMICON_DISK2            152
#define IDI_CUSTOMICON_FILES1           153
#define IDI_CUSTOMICON_FILES2           154
#define IDI_CUSTOMICON_FOLDER2          155
#define IDI_CUSTOMICON_FOLDER1          156
#define IDI_CUSTOMICON_MAIL1            157
#define IDI_CUSTOMICON_MAIL2            158
#define IDI_CUSTOMICON_NOTE1            159
#define IDI_CUSTOMICON_NOTE2            160
#define IDI_CUSTOMICON_PEN1             161
#define IDI_CUSTOMICON_PEN2             162
#define IDI_CUSTOMICON_PENCIL1          163
#define IDI_CUSTOMICON_PENCIL2          164
#define IDI_CUSTOMICON_PHONE1           165
#define IDI_CUSTOMICON_PHONE2           166
#define IDI_CUSTOMICON_POINT1           167
#define IDI_CUSTOMICON_POINT2           168
#define IDI_CUSTOMICON_SERCURITY        169
#define IDI_CUSTOMICON_SECURITY2        170
#define IDD_AUTOPANSPEED                172
#define IDD_FIXEDREGION                 173
#define IDI_ICONCROSSHAIR               174
#define IDB_BITMAP3                     175
#define IDD_AUDIODIALOG                 176
#define IDD_KEYSHORTCUTS                177
#define IDD_ANNOTATION                  179
#define IDD_TEXTOPTIONS                 180
#define IDB_TOOLBAR24                   182
#define IDB_TOOLBAR256                  183
#define IDB_TOOLBARMASK                 185
#define IDR_TRAYMENU                    186
#define IDB_BITMAP4                     189
#define IDD_AUTOSEARCH                  190
#define IDD_TROUBLESHOOT                191
#define IDR_CONTEXTMENU                 192
#define IDD_RESIZE                      192
#define IDD_TEXTDIALOG                  193
#define IDR_ANNOTATIONMENU              193
#define IDI_ICONJUSTIFYLEFT             194
#define IDI_ICONJUSTIFYCENTER           195
#define IDI_ICONJUSTIFYRIGHT            196
#define IDD_SYNCHRONIZATION             196
#define IDD_PRESETTIME                  197
#define IDR_CONTEXTLANGUAGE             198
#define IDD_TRANSPARENCY                199
#define IDD_TRANSPARENCYRATE2           199
#define IDD_NEWSHAPE                    200
#define IDD_EDITIMAGE                   201
#define IDC_CURSORDROPPER               205
#define IDC_CURSORDRAG                  207
#define IDC_CURSOR4                     208
#define IDC_RADIO1                      1000
#define IDC_COMPRESSORS                 1000
#define IDC_INTERLEAVESECONDS           1001
#define IDC_RADIO3                      1001
#define IDC_RADIO2                      1002
#define IDC_CURSOR1                     1003
#define IDC_RADIO4                      1003
#define IDC_CURSOR2                     1004
#define IDC_CURSOR3                     1005
#define IDC_HIGHLIGHTCURSOR             1006
#define IDC_SLIDER1                     1007
#define IDC_FPS                         1007
#define IDC_HIGHLIGHTSIZE               1007
#define IDC_PANSLIDER                   1007
#define IDC_SLIDERX                     1007
#define IDC_VOLUMESLIDER                1007
#define IDC_TRANSSLIDER                 1007
#define IDC_WIDTHSLIDER                 1007
#define IDC_COMBO2                      1008
#define IDC_HIGHLIGHTSHAPE              1008
#define IDC_SLIDERY                     1008
#define IDC_HEIGHTSLIDER                1008
#define IDC_RATESLIDER                  1008
#define IDC_CUSTOMCURSOR                1009
#define IDC_STOPKEY                     1010
#define IDC_FILECURSOR                  1011
#define IDC_PREVKEY                     1011
#define IDC_ICONCURSOR                  1012
#define IDC_CANCELKEY                   1012
#define IDC_GROUPBOX                    1013
#define IDC_WIDTH                       1013
#define IDC_SHOWKEY                     1013
#define IDC_MAXSPEED                    1014
#define IDC_HEIGHT                      1014
#define IDC_MSG                         1015
#define IDC_STATIC_SIZE                 1016
#define IDC_X                           1016
#define IDC_STATIC_SHAPE                1017
#define IDC_Y                           1017
#define IDC_STATIC_HALFSIZE             1018
#define IDC_CHOOSE                      1019
#define IDC_COMPRESSEDFORMATTAG         1020
#define IDC_COMPRESSEDFORMAT            1021
#define IDC_IFACTOR                     1022
#define IDC_INTERLEAVE                  1023
#define IDC_RECORDKEY                   1025
#define IDC_AUTO                        1026
#define IDC_NEXTKEY                     1026
#define IDC_ADJUST                      1027
#define IDC_EDITCAPTION                 1029
#define IDC_DATE                        1030
#define IDC_CAPTION                     1031
#define IDC_GRAPHICS                    1032
#define IDC_DATETIME                    1033
#define IDC_FILEIMAGE                   1034
#define IDC_NUMSECONDS                  1034
#define IDC_TOPLEFT                     1035
#define IDC_IMAGEPATH                   1036
#define IDC_MIDDLELEFT                  1036
#define IDC_BOTTOMLEFT                  1037
#define IDC_TOPCENTRE                   1038
#define IDC_MIDDLECENTRE                1039
#define IDC_BOTTOMCENTRE                1040
#define IDC_TOPRIGHT                    1041
#define IDC_MIDDLERIGHT                 1042
#define IDC_BOTTOMRIGHT                 1043
#define IDC_TEXTCOLOR_STATIC            1044
#define IDC_TEXTCOLOR_STATIC2           1045
#define ID_BORDERCOLOR                  1045
#define IDC_ADDBORDER                   1046
#define IDC_FIXEDTOPLEFT                1047
#define IDC_TEXT1                       1047
#define IDC_TEXT2                       1048
#define IDC_SUPPORTMOUSEDRAG            1048
#define IDC_INTERLEAVEFRAMES            1049
#define IDC_CLOSE                       1049
#define IDC_SOUNDDEVICE                 1050
#define IDC_STATICVOLUME                1051
#define IDC_STATICINFO                  1052
#define IDC_CHECK1                      1053
#define IDC_LIST1                       1053
#define IDC_TAB1                        1054
#define IDC_CHECK2                      1054
#define IDC_BUTTONLINK                  1055
#define IDC_EDIT1                       1055
#define IDC_CTRL1                       1056
#define IDC_TRANSTEXT                   1057
#define IDC_ALT1                        1057
#define IDC_SYSTEMRECORD                1057
#define IDC_SHIFT1                      1058
#define IDC_RATETEXT                    1058
#define IDC_IMAGEFILETEXT               1059
#define IDC_CTRL2                       1059
#define IDC_BUTTON1                     1060
#define IDC_ALT2                        1060
#define IDC_NAME                        1061
#define IDC_SHIFT2                      1061
#define IDC_EDIT3                       1062
#define IDC_CTRL3                       1062
#define IDC_COLOR                       1063
#define IDC_ALT3                        1063
#define IDC_COLORSTATIC                 1064
#define IDC_SHIFT3                      1064
#define IDC_COLOR3                      1065
#define IDC_CTRL4                       1065
#define IDC_BORDERSIZE                  1066
#define IDC_ALT4                        1066
#define IDC_COLOR2                      1067
#define IDC_SHIFT4                      1067
#define IDC_COLORSTATIC2                1068
#define IDC_CTRL5                       1068
#define IDC_STATIC1                     1069
#define IDC_ALT5                        1069
#define IDC_BORDERSTATIC                1070
#define IDC_SHIFT5                      1070
#define IDC_CTRL6                       1071
#define IDC_SPIN1                       1072
#define IDC_ALT6                        1072
#define IDC_STATICCHOOSE                1073
#define IDC_SHIFT6                      1073
#define IDC_STATICWIDTH                 1074
#define IDC_STATICHEIGHT                1075
#define IDC_KEYFRAMES                   1153
#define IDC_KEYFRAMES2                  1154
#define IDC_STATIC_KEYFRAMES            1277
#define IDC_STATIC_KEYFRAMES2           1278
#define IDC_STATIC_KEYFRAMES3           1279
#define IDC_QUALITY_SLIDER              1280
#define IDC_STATIC_QUALITY_LABEL        1281
#define IDC_QUALITY                     1289
#define IDC_COMBO1                      1290
#define IDC_RECORDFORMAT                1290
#define IDC_PREDEFINEDSHAPE             1290
#define IDC_COMBO3                      1291
#define IDC_INPUTDEVICE                 1291
#define IDD_ABOUTBOX                    5100
#define IDD_VIDEOOPTIONS                5101
#define IDD_GRAPHICSOPTIONS             5102
#define IDD_AUDIOWAVEOUT                5102
#define IDD_SCREENANNOTATIONS2          5103
#define IDD_TRANSPARENCYRATE            5104
#define IDD_TRANSRATE                   5104
#define IDR_MAINFRAME                   5128
#define IDR_MAINFRAMESMALL              5129
#define IDR_MAINFRAME1                  5129
#define IDB_BITMAP1                     5130
#define IDR_CONTEXTEDITOBJ              5130
#define IDR_CONTEXTEDITLAYOUT           5131
#define IDR_CONTEXTVIDEO                5132
#define ID_REGION_RUBBER                32771
#define ID_REGION_PANREGION             32772
#define ID_RECORD                       32773
#define ID_STOP                         32774
#define ID_PLAY                         32775
#define ID_REGION_TEST                  32776
#define ID_FILE_VIDEOOPTIONS            32777
#define ID_OPTIONS_CURSOROPTIONS        32778
#define ID_OPTIONS_AUTOPAN              32779
#define ID_OPTIONS_ATUOPANSPEED         32780
#define ID_REGION_FULLSCREEN            32781
#define ID_REGION_WINDOW                32784
#define ID_OPTIONS_MINIMIZEPROGRAMONSTARTRECORDING 32785
#define ID_OPTIONS_HIDEFLASHINGRECTANGLEDURINGRECORDING 32786
#define ID_OPTIONS_MINIMIZEONSTART      32787
#define ID_OPTIONS_PROGRAMOPTIONS_PLAYAVIFILEWHENRECORDINGSTOPS 32788
#define ID_OPTIONS_HIDEFLASHING         32789
#define ID_OPTIONS_PROGRAMOPTIONS_PLAYAVI 32790
#define ID_HELP_WEBSITE                 32791
#define ID_HELP_HELP                    32792
#define ID_VIEW_COMPACTVIEW             32793
#define ID_PAUSE                        32796
#define ID_VIEW_BUTTONVIEW              32797
#define ID_OPTIONS_RECORDAUDIO          32798
#define ID_OPTIONS_AUDIOOPTIONS         32799
#define ID_OPTIONS_AUDIOFORMAT          32800
#define ID_HELP_FAQ                     32801
#define ID_OPTIONS_KEYBOARDSHORTCUTS    32802
#define ID_VIEW_BUTTONSVIEW             32803
#define ID_VIEWTYPE                     32804
#define ID_VIEW_NORMALVIEW              32805
#define ID_OPTIONS_PROGRAMOPTIONS_SAVESETTINGSONEXIT 32806
#define ID_OPTIONS_RECORDINGTHREADPRIORITY_NORMAL 32807
#define ID_OPTIONS_RECORDINGTHREADPRIORITY_ABOVENORMAL 32808
#define ID_OPTIONS_RECORDINGTHREADPRIORITY_HIGHEST 32809
#define ID_OPTIONS_RECORDINGTHREADPRIORITY_TIMECRITICAL 32810
#define ID_OPTIONS_CAPTURETRANS         32811
#define ID_OPTIONS_TEMPDIR_WINDOWS      32812
#define ID_OPTIONS_TEMPDIR_INSTALLED    32813
#define ID_OPTIONS_TEMPDIR_USER         32814
#define ID_OPTIONS_TEST                 32815
#define ID_OPTIONS_RECORDAUDIO_DONOTRECORDAUDIO 32816
#define ID_OPTIONS_RECORDAUDIO_RECORDFROMSPEAKERS 32817
#define ID_OPTIONS_RECORDAUDIOMICROPHONE 32818
#define ID_OPTIONS_AUDIOSPEAKERS        32819
#define ID_OPTIONS_PROGRAMOPTIONS_TROUBLESHOOT 32820
#define ID_OPTIONS_PROGRAMOPTIONS_CAMSTUDIOPLAY 32821
#define ID_CONTEXT_CLOSE                32821
#define ID_OPTIONS_PROGRAMOPTIONS_DEFAULTPLAY 32822
#define ID_CONTEXT_CLOSEALL             32822
#define ID_OPTIONS_PROGRAMOPTIONS_NOPLAY 32823
#define ID_CONTEXT_SAVELAYOUT           32823
#define ID_HELP_DONATIONS               32824
#define ID_CONTEXT_RESIZE               32824
#define ID_OPTIONS_PROGRAMOPTIONS_PLAYAVIFILEWHENRECORDINGSTOPS_USECAMSTUDIOPLAYER20 32825
#define ID_CONTEXT_EDITTEXT             32825
#define ID_CONTEXT_REFRESH              32826
#define ID_VIEW_SCREENANNOTATIONS       32826
#define ID_SCRIPT_WESTERN               32827
#define ID_SCRIPT_BALTIC                32828
#define ID_SCRIPT_CHINESEBIG5           32829
#define ID_SCRIPT_DEFAULT               32830
#define ID_SCRIPT_EASTEUROPE            32831
#define ID_SCRIPT_CHINESEGB2312         32832
#define ID_EDITLAYOUT_LIBRARY_NEWLIBRARY 32832
#define ID_SCRIPT_GREEK                 32833
#define ID_EDITLAYOUT_LIBRARY_OPENLIBRARY 32833
#define ID_SCRIPT_HANGUL                32834
#define ID_EDITLAYOUT_LIBRARY_CLOSELIBRARY 32834
#define ID_VIEW_VIDEOANNOTATIONS        32834
#define ID_SCRIPT_MAC                   32835
#define ID_CONTEXTVIDEO_SOURCEFORMAT    32835
#define ID_SCRIPT_OEM                   32836
#define ID_CONTEXTVIDEO_VIDEOSOURCE     32836
#define ID_SCRIPT_RUSSIAN               32837
#define ID_CONTEXTVIDEO_EDITTRANSPARENCYREFRESHRATE 32837
#define ID_OPTIONS_CLOSESCREENANNOTATIONS 32837
#define ID_SCRIPT_JAPANESESHIFTJIS      32838
#define ID_CONTEXTVIDEO_EDITTRANSPARENCY 32838
#define ID_SCRIPT_SYMBOL                32839
#define ID_OPTIONS_AUDIOOPTIONS_AUDIOVIDEOSYNCHRONIZATION 32839
#define ID_SCRIPT_TURKISH               32840
#define ID_HELP_SHAPES                  32840
#define ID_SCRIPT_JOHABKOREAN           32841
#define ID_HELP_SHAPETOPICS_INSTANTIATINGASHAPE 32841
#define ID_SCRIPT_HEBREW                32842
#define ID_HELP_SHAPETOPICS_EDITINGASHAPE 32842
#define ID_SCRIPT_ARABIC                32843
#define ID_HELP_SHAPETOPICS_EDITINGTEXT 32843
#define ID_SCRIPT_THAI                  32844
#define ID_HELP_SHAPETOPICS_EDITINGIMAGE 32844
#define ID_CONTEXT_ANTIALIAS_NOANTIALIAS 32845
#define ID_HELP_SHAPETOPICS_EDITINGTRANSPARENCY 32845
#define ID_CONTEXT_ANTIALIAS_ANTIALIASX2 32846
#define ID_HELP_SHAPETOPICS_RESIZINGSHAPES 32846
#define ID_CONTEXT_ANTIALIAS_ANTIALIASX3SLOWEST 32847
#define ID_HELP_SHAPETOPICS_MANAGINGSHAPES 32847
#define ID_CONTEXT_EDITTRANSPARENCY     32848
#define ID_HELP_SHAPETOPICS_CREATINGANEWSHAPE 32848
#define ID_CONTEXT_SAVE                 32849
#define ID_HELP_LAYOUTS                 32849
#define ID_EDITOBJ_NEWOBJECT            32850
#define ID_EDITOBJ_EDITIMAGE            32851
#define ID_EDITOBJ_EDITTEXT             32852
#define ID_EDITOBJ_COPY                 32853
#define ID_EDITOBJ_PASTE                32854
#define ID_HELP_VIDEOANNOTATIONS        32854
#define ID_EDITOBJ_REMOVE               32855
#define IDR_ANN_SAVELAYOUT              32856
#define ID_EDITOBJ_LIBRARY_NEWLIBRARY   32857
#define IDD_ANN_OPENSHAPELIBRARAY       32857
#define ID_EDITOBJ_LIBRARY_OPENLIBRARY  32858
#define ID_EDITOBJ_LIBRARY_CLOSELIBRARY 32859
#define ID_EDITOBJ_EDITTRANSPARENCY     32862
#define ID_CONTEXT_EDITIMAGE            32863
#define ID_CONTEXT_CLONE                32864
#define ID_EDITOBJ_TESTEDIT             32865
#define ID_EDITLAYOUT_OPENLAYOUT        32866
#define ID_EDITLAYOUT_SAVELAYOUT        32867
#define ID_EDITLAYOUT_CLOSEALLOBJECTS   32868
#define ID_EDITLAYOUT_LAYOUTSHORTCUTS   32869
#define ID_LIBRARY_OPENSHAPELIBRARY     32880
#define ID_LIBRARY_SAVESHAPELIBRARY     32881
#define ID_LIBRARY_NEWSHAPELIBRARY      32882
#define ID_LIBRARY_OPENLAYOUTLIBRARY    32883
#define ID_LIBRARY_SAVELAYOUTLIBRARY    32884
#define ID_LIBRARY_NEWLAYOUTLIBRARY     32885
#define ID_OBJECTS_COPY                 32886
#define ID_OBJECTS_REMOVE               32887
#define ID_OBJECTS_PASTE                32888
#define ID_OBJECTS_EDITTEXT             32889
#define ID_OBJECTS_EDITIMAGE            32890
#define ID_OBJECTS_EDITTRANSAPRENCY     32891
#define ID_OBJECTS_EDITNAME             32892
#define ID_OBJECTS_CLOSEALLOBJECTS      32893
#define ID_LIBRARY_INSERTSHAPELIBARAY   32894
#define ID_OBJECTS_MOVEITEMUP           32895
#define ID_OBJECTS_MOVEITEMDOWN         32896
#define ID_TOOLS_SWFPRODUCER            32897
#define ID_OPTIONS_SWF_LAUNCHHTML       32898
#define ID_OPTIONS_SWF_DELETEAVIFILE    32899
#define ID_OPTIONS_SWF_DISPLAYPARAMETERS 32900
#define ID_AVISWF                       32902
#define ID_OPTIONS_NAMING_ASK           32903
#define ID_OPTIONS_PROGRAMOPTIONS_NAMINGOFFILES_AUTOMATICFILENAMINGUSEDATETIME 32904
#define ID_OPTIONS_PROGRAMOPTIONS_SAVINGOFAVINAMING_AUTOMATICFILENAMINGFIXEDNAME 32905
#define ID_OPTIONS_NAMING_AUTODATE      32906
#define ID_OPTIONS_PROGRAMOPTIONS_PRESETTIME 32907
#define IDS_STRING_NOTE                 61446
#define IDS_STRING_INTERLEAVE1          61447
#define IDS_STRING_NOINPUT1             61448
#define IDS_STRING_ERRVOLCTRL1          61449
#define IDS_STRING_ERRVOLREC            61450
#define IDS_STRING_NOINPUT2             61451
#define IDS_STRING_ERRVOLCTRL2          61452
#define IDS_STRING_WIDTHGREATER         61453
#define IDS_STRING_WIDTHSMALLER         61454
#define IDS_STRING_HEIGHTGREATER        61455
#define IDS_STRING_HEIGHTSMALLER        61456
#define IDS_STRING_LEFTGREATER          61457
#define IDS_STRING_LEFTSMALLER          61458
#define IDS_STRING_TOPGREATER           61459
#define IDS_STRING_TOPSMALLER           61460
#define IDS_STRING_VALUEEXCEEDWIDTH     61461
#define IDS_STRING_VALUEEXCEEDHEIGHT    61462
#define IDS_STRING_KEYRECORD            61463
#define IDS_STRING_KEYCANCEL            61464
#define IDS_STRING_KEYSTOP              61465
#define IDS_STRING_STOPBEFOREEXIT       61466
#define IDS_STRING_EXITSET              61467
#define IDS_STRING_TIMELAPSELESS        61468
#define IDS_STRING_TIMELAPSEMORE        61469
#define IDS_STRING_KEYFRAMES1           61470
#define IDS_STRING_PLAYBACKRATE         61471
#define IDS_STRING_NOCREATEWFILE        61472
#define IDS_STRING_FILECREATIONERROR    61473
#define IDS_STRING_NOSOUNDTRACK         61474
#define IDS_STRINGFILECREATION2         61475
#define IDS_STRING_FILECREATION3        61476
#define IDS_STRING_NOMERGE              61477
#define IDS_STRING_FILECREATION4        61478
#define IDS_STRING_ERRPLAYER            61479
#define IDS_STRING_VERSIONOLD           61480
#define IDS_STRING_ERRAVIDEFAULT        61481
#define IDS_STRING_ERRCREATEAVI         61482
#define IDS_STRING_ERRFRAME             61483
#define IDS_STRING_WAVEINERR            61484
#define IDS_STRING_ERRSOUND             61485
#define IDS_STRING_AUDIOBUF             61486
#define IDS_STRING_ERRSOUND2            61487
#define IDS_STRING_NOINPUT3             61488
#define IDS_STRING_METRICSFAILED        61489
#define IDS_STRING_GALLOC               61490
#define IDS_STRING_NOOPENVIDEO          61491
#define IDS_STRING_NOOPENSREAM          61492
#define IDS_STRING_NOCREATESTREAM       61493
#define IDS_STRING_NOOPENAUDIO          61494
#define IDS_STRING_NOEDITAUDIO          61495
#define IDS_STRING_NOVERIFYVIDEO        61496
#define IDS_STRING_NOVERIFYAUDIO        61497
#define IDS_STRING_NOMERGE1             61498
#define IDS_STRING_NOAUDIOCOMPRESS      61499
#define IDS_STRING_NOMERGE2             61500
#define IDS_STRING_GALLOCVCM            61501
#define IDS_STRING_FAILALLOCVCM         61502
#define IDS_STRING_COMPRESSORSTATE      61503
#define IDS_STRING_SETCOMPRESSOR        61504
#define IDS_STRING_UNNECESSARY          61505
#define IDS_STRING_ASKQUESTIONS         61506
#define IDS_STRING_ANALYZE              61507
#define IDS_STRING_TESTINGLINE          61508
#define IDS_STRING_SETTINGLINE          61509
#define IDS_STRING_NODETECT             61510
#define IDS_STRING_MANUALSEARCH         61511
#define IDS_STRING_MANUAL               61512
#define IDS_STRING_GETSELCTRL           61513
#define IDS_STRING_UNINIT               61514
#define IDS_STRING_INIT                 61515
#define IDS_STRING_MCIWAVE              61516
#define IDS_STRING_HEARTONES            61517
#define IDS_STRING_RECLINE              61518
#define IDS_STRING_HEARSEARCH           61519
#define IDS_STRING_ANALINE              61520
#define IDS_STRING_LINEDETECTED         61521
#define IDS_STRING_AUTODETECTFAILS      61522
#define IDS_STRING_COMPRESSINGAUDIO     61523
#define IDS_STRING_CURRFRAME            61524
#define IDS_STRING_TIMEELASPED          61525
#define IDS_STRING_NUMCOLORS            61526
#define IDS_STRING_CODEC                61527
#define IDS_STRING_ACTUALRATE           61528
#define IDS_STRING_DIMENSION            61529
#define IDS_STRING_NOTALL               61530
#define IDS_STRING_ERRSND               61531
#define IDS_STRING_NOAUDIOOUTPUT        61532
#define IDS_STRING_WSETVOL              61533
#define IDS_STRING_WGETVOL              61534
#define IDS_STRING_WGETVOLCTRL          61535
#define IDS_STRING_WVOLINIT             61536
#define IDS_STRING_OUTOFMEM             61537
#define IDS_STRING_ERRDESCENT           61538
#define IDS_STRING_ERRDEFAULTPLAYER     61539
#define IDS_STRING_NODETECTLINE         61540
#define IDS_STRING_LINEDETECTEDTH       61541
#define IDS_STRINGSPRKEY                61542
#define IDS_STRINGSRKEY                 61543
#define IDS_STRINGCRKEY                 61544
#define IDS_STRINGNLKEY                 61545
#define IDS_STRINGPLKEY                 61546
#define IDS_STRINGSHLKEY                61547
#define IDS_STRINGSAMEKEY               61548
#define IDS_STRINGINSHAPEFILE           61549
#define IDS_STRING_EOSFS                61550
#define IDS_STRINGINVLAYOUTFILE         61551
#define IDS_STRING_EOLFS                61552
#define IDS_STRINGWIDTHLESS20           61553
#define IDS_STRINGWIDTHLARGER           61554
#define IDS_STRINGHEIGHTLESS20          61555
#define IDS_STRINGHEIGHTLARGER          61556
#define IDS_STRINGINVIMGFILE            61557
#define IDS_STRING_SHAPES               61558
#define IDS_STRING_LAYOUT               61559
#define IDS_STRING_WORKSWINXP           61560
#define IDS_STRINGCANNOTSAVEO           61561
#define IDS_STRINGSAVECL                61562
#define IDS_STRINGcANNOTSAVEOL          61563
#define IDS_STRING_AVAILXP              61564
#define IDS_STRING_TRANSBLAHBLAH        61565
#define _APS_NEXT_STRNG_VALUE           61566
#define IDS_STRING_NOWEBCAM             61566
#define IDS_STRINGSAVECLLA              61567
#define IDS_STRING_UNSSC                61568
#define IDS_ERRPPRODUCER                61569
#define IDS_RECAVI                      61570
#define IDS_RECSWF                      61571

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        198
#define _APS_NEXT_COMMAND_VALUE         32908
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
